--- 
- name: restart nginx 
  service: name=nginx 
           enabled=yes 
           state=restarted 

- name: start mysql 
  service: name=mysql 
           enabled=yes 
           state=started 

- name: restart mysql 
  service: name=mysql 
           enabled=yes 
           state=restarted
